# Site settings
title: HootHub
email: hoothub@ch.tudelft.nl
description: > # this means to ignore newlines until "baseurl:"
  HootHub is the development platform for W.I.S.V. 'Christiaan Huygens' 
baseurl: "/hoothub" # the subpath of your site, e.g. /blog/
url: "http://wisv.ch/hoothub" # the base hostname & protocol for your site
twitter_username: 
github_username:  WISVCH

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: false
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown

kramdown:
  input: GFM
